name: Build and Publish .NET MAUI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        dotnet-version: [8.x]
        include:
          - os: macos-latest
            target-framework: net8.0-maccatalyst
            runtime-identifier: osx-x64
          - os: macos-latest
            target-framework: net8.0-maccatalyst
            runtime-identifier: osx-arm64
          - os: windows-latest
            target-framework: net8.0-windows10.0.19041.0
            runtime-identifier: [win-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install .NET MAUI Workload
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish -c Release -r ${{ matrix.runtime-identifier }} -f ${{ matrix.target-framework }} /p:PublishDir=./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime-identifier }}-app
          path: ./artifacts
