name: Build and Publish .NET MAUI App

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        runtime-identifier: [win-x64, maccatalyst-x64, maccatalyst-arm64]
        dotnet-version: [8.x]
        include:
          - runtime-identifier: win-x64
            os: windows-latest
            target-framework: net8.0-windows10.0.19041.0
          - runtime-identifier: maccatalyst-x64
            os: macos-latest
            target-framework: net8.0-maccatalyst
          - runtime-identifier: maccatalyst-arm64
            os: macos-latest
            target-framework: net8.0-maccatalyst
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install .NET MAUI Workload
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and Publish (Windows)
        if: ${{ matrix.os == windows-latest }}
        run: dotnet publish -c Release -f ${{ matrix.target-framework }} -o "${{ github.workspace }}/artifacts"

      - name: Build and Publish (Mac)
        if: ${{ matrix.os == macos-latest }}
        run: dotnet publish -c Release -r ${{ matrix.runtime-identifier }} -f ${{ matrix.target-framework }} -o "${{ github.workspace }}/artifacts"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runtime-identifier }}-app
          path: ./artifacts
